services:
  - type: web
    name: location-parser
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd app && npm install
    startCommand: cd app && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
